// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlJrBkRJ_0c0ykgjUDn7LNNchejg0DKJE',
    appId: '1:80046510853:web:f4357c1dc1effd4cf9dd6c',
    messagingSenderId: '80046510853',
    projectId: 'to-do-a0180',
    authDomain: 'to-do-a0180.firebaseapp.com',
    storageBucket: 'to-do-a0180.firebasestorage.app',
    measurementId: 'G-LGKLP6243N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgNIe5Lc3ING6dUCyUKVoLlMX6_4SsJOc',
    appId: '1:80046510853:android:b8943e20b6e33f9ff9dd6c',
    messagingSenderId: '80046510853',
    projectId: 'to-do-a0180',
    storageBucket: 'to-do-a0180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM-K-DtdFnxaz_x5WHxZbgIiuYE8q6VXg',
    appId: '1:80046510853:ios:dd61a83204ed00eef9dd6c',
    messagingSenderId: '80046510853',
    projectId: 'to-do-a0180',
    storageBucket: 'to-do-a0180.firebasestorage.app',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM-K-DtdFnxaz_x5WHxZbgIiuYE8q6VXg',
    appId: '1:80046510853:ios:dd61a83204ed00eef9dd6c',
    messagingSenderId: '80046510853',
    projectId: 'to-do-a0180',
    storageBucket: 'to-do-a0180.firebasestorage.app',
    iosBundleId: 'com.example.toDoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlJrBkRJ_0c0ykgjUDn7LNNchejg0DKJE',
    appId: '1:80046510853:web:57ac424fcc0512c5f9dd6c',
    messagingSenderId: '80046510853',
    projectId: 'to-do-a0180',
    authDomain: 'to-do-a0180.firebaseapp.com',
    storageBucket: 'to-do-a0180.firebasestorage.app',
    measurementId: 'G-BYQ9NW12PG',
  );

}